# Generated by Django 5.0.6 on 2025-12-26 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="duedate",
        ),
        migrations.AlterField(
            model_name="post",
            name="memo",
            field=models.TextField(blank=True, verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="タイトル"),
        ),
        migrations.AlterField(
            model_name="postfile",
            name="file",
            field=models.FileField(upload_to="post_files/", verbose_name="添付ファイル"),
        ),
        migrations.AlterField(
            model_name="postfile",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="case.post",
                verbose_name="事案",
            ),
        ),
    ]
