# Generated by Django 5.0.6 on 2026-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case", "0002_remove_post_duedate_alter_post_memo_alter_post_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="entry_date",
            field=models.DateField(blank=True, null=True, verbose_name="記入日"),
        ),
    ]
