# Generated by Django 5.0.6 on 2026-01-12 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case", "0003_post_entry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postfile",
            name="uploaded_at",
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="entry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="memo",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="priority",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="postfile",
            name="file",
            field=models.FileField(upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="postfile",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="case.post",
            ),
        ),
    ]
