# Generated by Django 5.0.6 on 2026-01-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case", "0004_remove_postfile_uploaded_at_alter_post_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(verbose_name="登録日時"),
        ),
    ]
