# Generated by Django 5.0.6 on 2026-01-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case", "0005_alter_post_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="entry_date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="priority",
        ),
        migrations.AddField(
            model_name="post",
            name="incident_date",
            field=models.DateField(blank=True, null=True, verbose_name="発生日"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="memo",
            field=models.TextField(),
        ),
    ]
