# Generated by Django 5.1.3 on 2026-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0006_remove_post_entry_date_remove_post_priority_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="incident_date",
        ),
        migrations.AddField(
            model_name="post",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="case_files/",
                verbose_name="添付ファイル",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="store_name",
            field=models.CharField(
                default="未設定!", max_length=100, verbose_name="店舗名"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
        ),
        migrations.AlterField(
            model_name="post",
            name="memo",
            field=models.TextField(blank=True, verbose_name="内容"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="件名"),
        ),
        migrations.DeleteModel(
            name="PostFile",
        ),
    ]
