# Generated by Django 5.1.3 on 2026-02-09 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case", "0007_remove_post_incident_date_post_file_post_store_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="記入日"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="タイトル"),
        ),
    ]
